name: chaldea
description: Chaldea Center

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.5.21+983

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: 3.32.8

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  android_id: ^0.4.0
  archive: ^4.0.1
  args: ^2.6.0
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.0
  cached_network_image_platform_interface: ^4.0.0
  carousel_slider: ^5.0.0
  catcher_2: ^2.1.0
  connectivity_plus: ^6.1.1
  # cookie_jar: ^4.0.1
  # crclib: ^3.0.0
  cross_file: ^0.3.3+5
  crypto: ^3.0.6
  csv: ^6.0.0
  cupertino_icons: ^1.0.6
  dart_des: ^1.0.2
  data_table_2: ^2.5.16
  device_info_plus: ^11.2.0
  dio: ^5.3.3
  # dio_cookie_manager: ^3.0.0
  dots_indicator: ^4.0.0
  equatable: ^2.0.5
  file_picker: ^10.1.7
  fl_chart: ^1.0.0
  flutter_cache_manager: ^3.3.1
  flutter_easyloading: ^3.0.5
  flutter_hooks: ^0.21.2
  flutter_local_notifications: ^19.0.0
  flutter_markdown: ^0.7.4
  # flutter_qjs: ^0.3.7
  flutter_js: ^0.8.5
  flutter_svg: ^2.0.7
  flutter_timezone: ^4.0.0
  font_awesome_flutter: ^10.6.0
  github: ^9.16.0
  hive: ^2.2.3
  home_widget: ^0.8.0
  html: ^0.15.3
  http: ^1.2.0
  image: ^4.5.0
  image_gallery_saver: # ^1.7.1
    git: https://github.com/chaldea-center/image_gallery_saver.git
  intl: ">=0.19.0 <0.21.0"
  json_annotation: ^4.9.0
  just_audio: ^0.10.2
  just_audio_windows: ^0.2.0
  # just_audio_mpv: ^0.1.4  # manually install mpv on linux
  kana_kit: ^2.1.1
  logger: ^2.3.0
  lpinyin: ^2.0.3
  markdown: ^7.0.0
  modal_bottom_sheet: ^3.0.0
  msgpack_dart: ^1.0.1
  octo_image: ^2.0.0
  package_info_plus: ^8.1.2
  pasteboard: ^0.4.0
  path: ^1.8.2
  path_provider: ^2.1.3
  permission_handler: ^12.0.0
  # pointycastle: ^3.9.1
  pool: ^1.5.0
  photo_view: ^0.15.0
  screenshot: ^3.0.0
  share_plus: ^11.0.0
  shared_preferences: ^2.2.0
  sliver_tools: ^0.2.12
  smooth_page_indicator: ^1.1.0
  string_validator: ^1.0.0
  table_sticky_headers: ^2.0.1
  timezone: ^0.10.0
  tray_manager: ^0.5.0
  tuple: ^2.0.1
  url_launcher: ^6.3.1
  uuid: ^4.3.3
  video_player: ^2.8.1
  video_player_win: ^3.1.0
  wakelock_plus: ^1.2.8
  web: ^1.1.0
  # webview_flutter: ^4.1.0
  # webview_flutter_web: ^0.2.2+1
  worker_manager: ^7.2.2
  window_manager: ^0.5.0
  countly_flutter_np: ^25.1.1
  google_mobile_ads: ^6.0.0
  # admanager_web: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.6.0
  flutter_lints: ^6.0.0
  json_serializable: ^6.9.0
  import_sorter: # ^4.6.0
    git: https://github.com/chaldea-center/import_sorter.git
  intl_utils: # ^2.6.1
    git: https://github.com/chaldea-center/intl_utils.git
  # flutter_launcher_icons: ^0.8.1

#flutter_icons:
#  #  image_path: "assets/images/icon-128x128.png"
#  ios: true # can specify file name here e.g. "My-Launcher-Icon"
#  image_path_ios: "res/img/launcher_icon/ic_ios.png"
#  android: true # can specify file name here e.g. "ic_launcher"
#  image_path_android: "res/img/launcher_icon/ic_android_foreground.png"
##  adaptive_icon_background: "#FFFFFF" # only available for Android 8.0 devices and above
##  adaptive_icon_foreground: "res/img/launcher_icon/ic_android_foreground.png" # only available for Android 8.0 devices and above

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - res/license/
    - res/assets/
    - res/img/
    - res/img/launcher_icon/
    - res/img/md/
    - res/js/
    - CHANGELOG.md
    - LICENSE
    - README.md
    - CONTRIBUTORS

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: RobotoMono
      fonts:
        - asset: res/fonts/RobotoMono-VariableFont_wght.ttf
        - asset: res/fonts/RobotoMono-Italic-VariableFont_wght.ttf
          style: italic

flutter_intl:
  enabled: true
  main_locale: en
