name: chaldea
description: Chaldea Center

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.2.6+922

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  android_id: ^0.1.3+1
  archive: ^3.3.1
  args: ^2.3.1
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.3
  cached_network_image_platform_interface: ^2.0.0
  carousel_slider: ^4.1.1
  catcher: # ^0.7.0
    git:
      url: https://github.com/narumi147/catcher.git
  connectivity_plus: ^3.0.2
  cookie_jar: ^3.0.1
  crclib: ^3.0.0
  cross_file: ^0.3.3+2
  crypto: ^3.0.2
  csv: ^5.0.1
  cupertino_icons: ^1.0.4
  dart_des: ^1.0.2
  data_table_2: ^2.3.10
  device_info_plus: ^8.0.0
  dio: ^5.0.1
  dio_cookie_manager: ^2.1.1
  dots_indicator: ^2.0.0
  file_picker: ^5.2.2
  fl_chart: ^0.61.0
  flutter_cache_manager: ^3.2.0
  flutter_easyloading: ^3.0.5
  flutter_email_sender: ^5.0.2
  flutter_hooks: ^0.18.5+1
  flutter_markdown: ^0.6.14
  flutter_picker: ^2.1.0
  # flutter_qjs: ^0.3.7
  flutter_js: ^0.6.0
  flutter_window_close: ^0.2.2
  font_awesome_flutter: ^10.1.0
  github: ^9.10.1
  hive: ^2.2.3
  html: ^0.15.0
  http: ^0.13.5
  image: ^4.0.15
  image_gallery_saver: # ^1.7.1
    git:
      url: https://github.com/artflutter/image_gallery_saver.git
      ref: 31b6648a6a2be85c32021f651a71a34f98ffaa67
  intl: ^0.17.0
  json_annotation: ^4.8.0
  just_audio: ^0.9.28
  just_audio_windows: ^0.2.0
  # just_audio_mpv: ^0.1.4  # manually install mpv on linux
  kana_kit: ^2.0.0
  logger: ^1.1.0
  lpinyin: ^2.0.3
  markdown: ^7.0.0
  modal_bottom_sheet:
    git:
      url: https://github.com/CoolDude53/modal_bottom_sheet.git
      ref: d3779be7d661481cc0d99090d6356a286ae4f86b
      path: modal_bottom_sheet
  octo_image: ^1.0.2
  package_info_plus: ^3.0.2
  path: ^1.8.2
  path_provider: ^2.0.10
  permission_handler: ^10.1.0
  pool: ^1.5.0
  photo_view: ^0.14.0
  rfc_6902: ^0.1.0
  ruby_text: ^3.0.1
  screenshot: ^1.2.3
  share_plus: ^6.3.0
  shared_preferences: ^2.0.15
  sliver_tools: ^0.2.6
  smooth_page_indicator: ^1.0.0+2
  string_validator: ^1.0.0
  system_tray: ^2.0.2
  table_sticky_headers: ^2.0.1
  tuple: ^2.0.1
  url_launcher: ^6.1.5
  uuid: ^3.0.5
  video_player: ^2.5.2
  video_player_win: ^2.0.0
  video_player_macos: # ^1.0.0
    git:
      url: https://github.com/ollydixon/flutter_macos_video_player
      path: packages/video_player/video_player_macos
      ref: bae932d006e9171fcb57becc7000513cea78076e
  webview_flutter: ^4.0.4
  webview_flutter_web: ^0.2.2+1
  worker_manager: ^5.0.3
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  dart_code_metrics: ^5.6.0
  flutter_lints: ^2.0.1
  json_serializable: ^6.6.1
  import_sorter: ^4.6.0
  intl_utils: # ^2.6.1
    git:
      url: https://github.com/chaldea-center/intl_utils
  # flutter_launcher_icons: ^0.8.1

#flutter_icons:
#  #  image_path: "assets/images/icon-128x128.png"
#  ios: true # can specify file name here e.g. "My-Launcher-Icon"
#  image_path_ios: "res/img/launcher_icon/ic_ios.png"
#  android: true # can specify file name here e.g. "ic_launcher"
#  image_path_android: "res/img/launcher_icon/ic_android_foreground.png"
##  adaptive_icon_background: "#FFFFFF" # only available for Android 8.0 devices and above
##  adaptive_icon_foreground: "res/img/launcher_icon/ic_android_foreground.png" # only available for Android 8.0 devices and above

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - doc/help/
    - doc/license/
    - res/assets/
    - res/img/
    - res/img/launcher_icon/
    - res/img/md/
    - res/js/
    - CHANGELOG.md
    - LICENSE
    - README.md
    - CONTRIBUTORS

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: RobotoMono
      fonts:
        - asset: res/fonts/RobotoMono-VariableFont_wght.ttf
        - asset: res/fonts/RobotoMono-Italic-VariableFont_wght.ttf
          style: italic

flutter_intl:
  enabled: true
  main_locale: en
