name: chaldea
description: Chaldea Center

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.6.7+670

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  archive: ^3.1.9
  auto_size_text: ^3.0.0
  baidu_mob_stat:
    git:
      url: https://github.com/narumishi/baidumobstat-flutter
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  catcher: ^0.6.9
  connectivity_plus: 1.0.8
  connectivity_plus_macos: 1.0.2  # 1.1.0: macOS deployment target 10.11 to 10.14
  crclib: ^3.0.0
  crypto: ^3.0.1
  csv: ^5.0.1
  cupertino_icons: ^1.0.4
  device_info_plus: ^3.2.1
  dio: ^4.0.4
  dio_cookie_manager: ^2.0.0
  dots_indicator: ^2.0.0
  file_picker: ^4.3.2
  fl_chart: ^0.41.0
  flutter_cache_manager: ^3.2.0
  flutter_easyloading: ^3.0.0
  flutter_email_sender: ^5.0.2
  flutter_markdown: ^0.6.8
  flutter_picker: ^2.0.2
  flutter_qjs: ^0.3.6
  font_awesome_flutter: ^9.2.0
  get: any
  hive: ^2.0.4
  html: ^0.15.0
  image: ^3.1.1
  image_gallery_saver: ^1.7.1
  intl: ^0.17.0
  json_annotation: ^4.4.0
  just_audio: ^0.9.18
  # comment in linux
  just_audio_libwinmedia: ^0.0.4
  kana_kit: ^2.0.0
  logger: ^1.1.0
  lpinyin: ^2.0.3
  modal_bottom_sheet: ^2.0.0
  open_file: ^3.2.1
  package_info_plus: ^1.3.0
  path_provider: ^2.0.8
  permission_handler: ^8.3.0
  pool: ^1.5.0
  photo_view: ^0.13.0
  rfc_6902: ^0.1.0
  screenshot: ^1.2.3
  share_plus: ^3.0.4
  shared_preferences: ^2.0.12
  sliver_tools: ^0.2.5
  smooth_page_indicator: ^1.0.0+2
  string_validator: ^0.3.0
  table_sticky_headers: ^2.0.0
  url_launcher: ^6.0.18
  uuid: ^3.0.5
  worker_manager: ^4.2.5
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  flutter_lints: ^1.0.4
  json_serializable: ^6.1.4
  intl_utils: ^2.6.1
  hive_generator: any
  # flutter_launcher_icons: ^0.8.1


#flutter_icons:
#  #  image_path: "assets/images/icon-128x128.png"
#  ios: true # can specify file name here e.g. "My-Launcher-Icon"
#  image_path_ios: "res/img/launcher_icon/ic_ios.png"
#  android: true # can specify file name here e.g. "ic_launcher"
#  image_path_android: "res/img/launcher_icon/ic_android_foreground.png"
##  adaptive_icon_background: "#FFFFFF" # only available for Android 8.0 devices and above
##  adaptive_icon_foreground: "res/img/launcher_icon/ic_android_foreground.png" # only available for Android 8.0 devices and above


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - doc/help/
    - doc/license/
    - res/data/
    - res/img/
    - res/img/launcher_icon/app_icon_logo.png
    - res/img/md/
    - res/js/
    - res/VERSION
    - CHANGELOG.md
    - LICENSE
    - README.md

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: RobotoMono
      fonts:
        - asset: res/fonts/RobotoMono-VariableFont_wght.ttf
        - asset: res/fonts/RobotoMono-Italic-VariableFont_wght.ttf
          style: italic

flutter_intl:
  enabled: true
  main_locale: zh
