name: Test

on:
  push:
    branches:
      - dev
      - main
  pull_request:
  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.19.0"

jobs:
  test:
    name: Test on linux
    runs-on: ubuntu-latest
    steps:
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true
          cache-key: flutter-ubuntu-latest-linux-${{ env.FLUTTER_VERSION }}
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libx11-dev pkg-config cmake ninja-build libblkid-dev
          sudo apt-get install -y libayatana-appindicator3-dev

      - name: flutter doctor
        run: |
          flutter config --enable-linux-desktop
          flutter doctor -v

      - name: Checkout chaldea code
        uses: actions/checkout@v3

      - name: Checkout chaldea data
        uses: actions/checkout@v3
        with:
          repository: chaldea-center/chaldea-data
          path: data/
      - run: mv data/dist data/game


      - run: flutter pub get
      - run: flutter test -d linux --dart-define=APP_PATH=$GITHUB_WORKSPACE/data/
